apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
spec:
  ports:
   - port: 4444
     targetPort: 4444
     name: port0
   - name: node
     protocol: TCP
     port: 5555
     targetPort: 5555  
  selector:
    app: selenium-hub
  type: NodePort
  sessionAffinity: None
