---
# Source: zalenium/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-zalenium
  labels:
    role: grid
    app: zalenium
    chart: zalenium-3.141.59
    release: vault
    heritage: Helm
    app.kubernetes.io/name: zalenium
    helm.sh/chart: zalenium-3.141.59
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
