---
# Source: zalenium/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vault-zalenium
  labels:
    role: grid
    app: zalenium
    chart: zalenium-3.141.59
    release: vault
    heritage: Helm
    app.kubernetes.io/name: zalenium
    helm.sh/chart: zalenium-3.141.59
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
spec:
  type: "NodePort"
  sessionAffinity: "None"
  ports:
  - name: hub
    port: 80
    targetPort: 4444
  selector:
    app.kubernetes.io/name: zalenium
    app.kubernetes.io/instance: vault
